services:
  rabbitmq:
    container_name: '${PROJECT_NAME:?must be set}-rabbitmq'
    environment:
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD:?must be set}'
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:?must be set}'
      RABBITMQ_DEFAULT_VHOST: '${RABBITMQ_VHOST:?must be set}'
      TZ: UTC
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - -q
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: '${PROJECT_NAME:?must be set}-rabbitmq'
    image: 'rabbitmq:4-management'
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    ports:
      - '${RABBITMQ_EXPOSE_HOST:?must be set}:${RABBITMQ_AMQP_EXPOSE_PORT:?must be set}:5672'
      - '${RABBITMQ_EXPOSE_HOST:?must be set}:${RABBITMQ_MANAGEMENT_EXPOSE_PORT:?must be set}:15672'
    restart: always
    stop_grace_period: 1m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - '${RABBITMQ_FILES_PATH:?must be set}:/var/lib/rabbitmq'
